[package]
name = "hello_world" # the name of the package
version = "0.1.0"    # the current version, obeying semver


[dependencies]
bcrypt = "0.8.2"
magic-crypt = "3.1.6"
base64 = "0.13.0"
regex = "1"

[[bin]]
name = "groupencoding"
path = "groupencoding.rs"