[package]
name = "hello_world" # the name of the package
version = "0.1.0"    # the current version, obeying semver


[dependencies]
event-listener = "2.5.2"
rand = "0.8.5"

[[bin]]
name = "interface"
path = "interface.rs"