CREATE TABLE groups (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(200) NOT NULL,
  completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE chats (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  groupId INTEGER NOT NULL,
  name VARCHAR(32) NOT NULL,
  message VARCHAR(128) NOT NULL,
  time DATETIME DEFAULT CURRENT_TIMESTAMP
);
