CREATE TABLE groups (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(16) NOT NULL,
  bio VARCHAR(128)
)

CREATE TABLE chats (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  groupId INTEGER NOT NULL,
  name VARCHAR(16) NOT NULL,
  message VARCHAR(128) NOT NULL,
  time DATETIME DEFAULT CURRENT_TIMESTAMP
);
